on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The target environment'
        required: true
        default: lz01
        type: choice
        options:
          - lz01
          - lz02
      appservice:
        description: 'App Service name'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

name: appdeploy
run-name: appdeploy | ${{ github.event.inputs.appservice }} | ${{ github.event.inputs.environment }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 'Clean workspace'
        run: |
          rm -f ${{ github.workspace }}/ui.zip
          rm -rf ${{ github.workspace }}/app

      - uses: actions/checkout@v7

      - name: 'Environment variables'
        run: |
          grep -v '^\s*#' config/global.env | grep -v '^\s*$' >>$GITHUB_ENV || true
          echo -e "\n" >>$GITHUB_ENV
          grep -v '^\s*#' config/${{ github.event.inputs.environment }}.env | grep -v '^\s*$' >>$GITHUB_ENV || true
          echo -e "\n" >>$GITHUB_ENV

      - name: 'Resource group'
        run: |
          NUMBER=$(grep number config/global.tfvars | cut -d= -f2 | tr -d ' "')
          LZ=$(grep '^lz ' config/${{ github.event.inputs.environment }}.tfvars | cut -d= -f2 | tr -d ' "')
          echo "RESOURCE_GROUP=rg${NUMBER}-${LZ}" >>$GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Setup uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Package
        run: |
          cd app/ui
          uv sync --frozen
          zip -r ../../ui.zip .

      - name: Deploy
        run: |
          az webapp config appsettings set \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ github.event.inputs.appservice }} \
            --settings SCM_DO_BUILD_DURING_DEPLOYMENT=false
          az webapp config set \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ github.event.inputs.appservice }} \
            --startup-file ".venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000"
          az webapp deploy \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ github.event.inputs.appservice }} \
            --src-path ui.zip \
            --type zip
